swagger: "2.0"
info: 
  version: "0.0.1"
  title: "cpuinfo"
  description: "A simple service to get cpuinfo as an example of using swagger-2.0 specification and codegen"
  termsOfService: "http://swagger.io/terms/"
  contact: 
    name: "Cloudmesh REST Service Example"
  license: 
    name: "Apache"
host: "localhost:8080"
basePath: "/"
schemes: 
  - "http"
consumes: 
  - "application/json"
produces: 
  - "application/json"
paths: 
  /cpu:
    get:
      tags:
        - CPU
      operationId: cpu.get_processor_name
      description: "Returns cpu information of the hosting server"
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "CPU info"
          schema: 
            $ref: "#/definitions/CPU"
  /prime:
    get:
      tags:
        - prime
      operationId: prime.isPrime
      description: "Returns whether the input is prime or not"
      produces:
        - "application/json"
      responses:
        "200":
          description: "Is Prime"
          schema:
            $ref: "#definitions/prime"
  /add:
    get:
      tags:
        - add
      operationId: add.add
      description: "Returns the sum of the two inputs"
      produces:
        - "application/json"
      responses:
        "200":
          description: "Adder"
          schema:
            $ref: "#definitions/add"
definitions:
  CPU:
    type: "object"
    required: 
      - "model"
    properties: 
      model:
        type: "string"
  prime:
    type: "object"
    required:
      - "model"
    properties:
      model:
        type: "string"
  add:
    type: "object"
    required:
      - "model"
    properties:
      model:
        type: "string"
