swagger: "2.0"
info: 
  version: "0.0.1"
  title: "spamInfo"
  description: "An intelligent system to determine whether a given email is spam or not"
  termsOfService: "http://swagger.io/terms/"
  contact: 
    name: "Spamalot"
  license: 
    name: "Apache"
host: "localhost:8080"
basePath: "/"
schemes: 
  - "http"
consumes: 
  - "application/json"
produces: 
  - "application/json"
paths: 
  /add/<n1>&<n2>:
    get:
      tags:
        - CPU
      operationId: add.add
      description: "Calculates sum"
      produces:
        - "application/json"
      responses:
        "200":
          description: "Adder"
          schema: {}
  /monkey.jpg:
    get:
      tags:
        - MONKEY
      operationId: showImage.showImage
      description: "Shows Image"
      produces:
        - "application/jpg"
      responses:
        "200":
          description: "Picture"
          schema: {}
